	data_path u0 (
		.clk_clk                                                       (<connected-to-clk_clk>),                                                       //                                               clk.clk
		.code_storage_enable_interface_enable                          (<connected-to-code_storage_enable_interface_enable>),                          //                     code_storage_enable_interface.enable
		.code_storage_write_interface_write_data                       (<connected-to-code_storage_write_interface_write_data>),                       //                      code_storage_write_interface.write_data
		.code_storage_write_interface_is_write                         (<connected-to-code_storage_write_interface_is_write>),                         //                                                  .is_write
		.code_storage_write_interface_write_line                       (<connected-to-code_storage_write_interface_write_line>),                       //                                                  .write_line
		.controller_enable_interface_enable                            (<connected-to-controller_enable_interface_enable>),                            //                       controller_enable_interface.enable
		.controller_use_z_interface_use_z                              (<connected-to-controller_use_z_interface_use_z>),                              //                        controller_use_z_interface.use_z
		.input_storage_is_write_interface_is_write                     (<connected-to-input_storage_is_write_interface_is_write>),                     //                  input_storage_is_write_interface.is_write
		.input_storage_write_interface_write_layer_index               (<connected-to-input_storage_write_interface_write_layer_index>),               //                     input_storage_write_interface.write_layer_index
		.input_storage_write_interface_write_row_index                 (<connected-to-input_storage_write_interface_write_row_index>),                 //                                                  .write_row_index
		.input_storage_write_interface_write_data                      (<connected-to-input_storage_write_interface_write_data>),                      //                                                  .write_data
		.label_storage_is_write_interface_is_write                     (<connected-to-label_storage_is_write_interface_is_write>),                     //                  label_storage_is_write_interface.is_write
		.label_storage_write_interface_write_layer_index               (<connected-to-label_storage_write_interface_write_layer_index>),               //                     label_storage_write_interface.write_layer_index
		.label_storage_write_interface_write_row_index                 (<connected-to-label_storage_write_interface_write_row_index>),                 //                                                  .write_row_index
		.label_storage_write_interface_write_data                      (<connected-to-label_storage_write_interface_write_data>),                      //                                                  .write_data
		.matrix_storage_locator_reset_interface_reset                  (<connected-to-matrix_storage_locator_reset_interface_reset>),                  //            matrix_storage_locator_reset_interface.reset
		.reset_reset_n                                                 (<connected-to-reset_reset_n>),                                                 //                                             reset.reset_n
		.weight_storage_is_update_interface_is_update                  (<connected-to-weight_storage_is_update_interface_is_update>),                  //                weight_storage_is_update_interface.is_update
		.weight_storage_is_write_interface_is_write                    (<connected-to-weight_storage_is_write_interface_is_write>),                    //                 weight_storage_is_write_interface.is_write
		.weight_storage_update_weight_interface_dc_dw                  (<connected-to-weight_storage_update_weight_interface_dc_dw>),                  //            weight_storage_update_weight_interface.dc_dw
		.weight_storage_update_weight_interface_layer_index            (<connected-to-weight_storage_update_weight_interface_layer_index>),            //                                                  .layer_index
		.weight_storage_update_weight_interface_row_index              (<connected-to-weight_storage_update_weight_interface_row_index>),              //                                                  .row_index
		.weight_storage_write_interface_write_layer_index              (<connected-to-weight_storage_write_interface_write_layer_index>),              //                    weight_storage_write_interface.write_layer_index
		.weight_storage_write_interface_write_row_index                (<connected-to-weight_storage_write_interface_write_row_index>),                //                                                  .write_row_index
		.weight_storage_write_interface_write_data                     (<connected-to-weight_storage_write_interface_write_data>),                     //                                                  .write_data
		.activate_to_diff_register_out_forward_interface_label         (<connected-to-activate_to_diff_register_out_forward_interface_label>),         //   activate_to_diff_register_out_forward_interface.label
		.activate_to_diff_register_out_forward_interface_dense_type    (<connected-to-activate_to_diff_register_out_forward_interface_dense_type>),    //                                                  .dense_type
		.activate_to_diff_register_out_forward_interface_backprop_cost (<connected-to-activate_to_diff_register_out_forward_interface_backprop_cost>), //                                                  .backprop_cost
		.activate_to_diff_register_out_forward_interface_w_row_index   (<connected-to-activate_to_diff_register_out_forward_interface_w_row_index>),   //                                                  .w_row_index
		.activate_to_diff_register_out_forward_interface_is_update     (<connected-to-activate_to_diff_register_out_forward_interface_is_update>),     //                                                  .is_update
		.activate_to_diff_register_out_forward_interface_w_layer_index (<connected-to-activate_to_diff_register_out_forward_interface_w_layer_index>), //                                                  .w_layer_index
		.activate_to_diff_register_out_cost_type_interface_cost_type   (<connected-to-activate_to_diff_register_out_cost_type_interface_cost_type>),   // activate_to_diff_register_out_cost_type_interface.cost_type
		.activate_to_diff_register_out_z_interface_z                   (<connected-to-activate_to_diff_register_out_z_interface_z>),                   //         activate_to_diff_register_out_z_interface.z
		.activate_to_diff_register_out_x_interface_x                   (<connected-to-activate_to_diff_register_out_x_interface_x>),                   //         activate_to_diff_register_out_x_interface.x
		.activate_to_diff_register_out_w_interface_w                   (<connected-to-activate_to_diff_register_out_w_interface_w>),                   //         activate_to_diff_register_out_w_interface.w
		.activate_to_diff_register_clock_clk                           (<connected-to-activate_to_diff_register_clock_clk>)                            //                   activate_to_diff_register_clock.clk
	);

