# TCL File Generated by Component Editor 20.1
# Wed Dec 23 22:30:37 ICT 2020
# DO NOT MODIFY


# 
# mult_matrix_prep "mult_matrix_prep" v1.0
#  2020.12.23.22:30:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mult_matrix_prep
# 
set_module_property DESCRIPTION ""
set_module_property NAME mult_matrix_prep
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mult_matrix_prep
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mult_matrix_prep
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mult_matrix_prep.sv SYSTEM_VERILOG PATH ../../mult_matrix_prep/mult_matrix_prep.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_size INTEGER 4
set_parameter_property data_size DEFAULT_VALUE 4
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size HDL_PARAMETER true
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point mult_matrix_prep
# 
add_interface mult_matrix_prep avalon end
set_interface_property mult_matrix_prep addressUnits WORDS
set_interface_property mult_matrix_prep associatedClock ""
set_interface_property mult_matrix_prep associatedReset ""
set_interface_property mult_matrix_prep bitsPerSymbol 8
set_interface_property mult_matrix_prep burstOnBurstBoundariesOnly false
set_interface_property mult_matrix_prep burstcountUnits WORDS
set_interface_property mult_matrix_prep explicitAddressSpan 0
set_interface_property mult_matrix_prep holdTime 0
set_interface_property mult_matrix_prep linewrapBursts false
set_interface_property mult_matrix_prep maximumPendingReadTransactions 0
set_interface_property mult_matrix_prep maximumPendingWriteTransactions 0
set_interface_property mult_matrix_prep readLatency 0
set_interface_property mult_matrix_prep readWaitTime 1
set_interface_property mult_matrix_prep setupTime 0
set_interface_property mult_matrix_prep timingUnits Cycles
set_interface_property mult_matrix_prep writeWaitTime 0
set_interface_property mult_matrix_prep ENABLED true
set_interface_property mult_matrix_prep EXPORT_OF ""
set_interface_property mult_matrix_prep PORT_NAME_MAP ""
set_interface_property mult_matrix_prep CMSIS_SVD_VARIABLES ""
set_interface_property mult_matrix_prep SVD_ADDRESS_GROUP ""

add_interface_port mult_matrix_prep input_stream beginbursttransfer Input data_size*size
add_interface_port mult_matrix_prep output_stream writeresponsevalid_n Output data_size*size
set_interface_assignment mult_matrix_prep embeddedsw.configuration.isFlash 0
set_interface_assignment mult_matrix_prep embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mult_matrix_prep embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mult_matrix_prep embeddedsw.configuration.isPrintableDevice 0

