# TCL File Generated by Component Editor 20.1
# Mon Dec 28 23:37:05 ICT 2020
# DO NOT MODIFY


# 
# clock_sum "clock_sum" v1.0
# Wachirawit Wacharak 2020.12.28.23:37:05
# Summarize clicks
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module clock_sum
# 
set_module_property DESCRIPTION "Summarize clicks"
set_module_property NAME clock_sum
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/utils
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME clock_sum
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL clock_sum
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file clock_sum.sv SYSTEM_VERILOG PATH ../clock_sum/clock_sum.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_a
# 
add_interface clock_a clock end
set_interface_property clock_a clockRate 0
set_interface_property clock_a ENABLED true
set_interface_property clock_a EXPORT_OF ""
set_interface_property clock_a PORT_NAME_MAP ""
set_interface_property clock_a CMSIS_SVD_VARIABLES ""
set_interface_property clock_a SVD_ADDRESS_GROUP ""

add_interface_port clock_a clk_a clk Input 1


# 
# connection point clock_b
# 
add_interface clock_b clock end
set_interface_property clock_b clockRate 0
set_interface_property clock_b ENABLED true
set_interface_property clock_b EXPORT_OF ""
set_interface_property clock_b PORT_NAME_MAP ""
set_interface_property clock_b CMSIS_SVD_VARIABLES ""
set_interface_property clock_b SVD_ADDRESS_GROUP ""

add_interface_port clock_b clk_b clk Input 1


# 
# connection point clock_out
# 
add_interface clock_out clock start
set_interface_property clock_out associatedDirectClock ""
set_interface_property clock_out clockRate 0
set_interface_property clock_out clockRateKnown false
set_interface_property clock_out ENABLED true
set_interface_property clock_out EXPORT_OF ""
set_interface_property clock_out PORT_NAME_MAP ""
set_interface_property clock_out CMSIS_SVD_VARIABLES ""
set_interface_property clock_out SVD_ADDRESS_GROUP ""

add_interface_port clock_out clk_out clk Output 1

