# TCL File Generated by Component Editor 20.1
# Thu Dec 31 21:15:43 ICT 2020
# DO NOT MODIFY


# 
# code_storage "code_storage" v1.0
# Wachirawit Wacharak 2020.12.31.21:15:43
# Use to store instruction
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module code_storage
# 
set_module_property DESCRIPTION "Use to store instruction"
set_module_property NAME code_storage
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/fetch_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME code_storage
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL code_storage
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file code_storage.sv SYSTEM_VERILOG PATH ../code_storage/code_storage.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter code_size INTEGER 12
set_parameter_property code_size DEFAULT_VALUE 12
set_parameter_property code_size DISPLAY_NAME code_size
set_parameter_property code_size TYPE INTEGER
set_parameter_property code_size UNITS None
set_parameter_property code_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property code_size HDL_PARAMETER true
add_parameter max_code_line INTEGER 100
set_parameter_property max_code_line DEFAULT_VALUE 100
set_parameter_property max_code_line DISPLAY_NAME max_code_line
set_parameter_property max_code_line TYPE INTEGER
set_parameter_property max_code_line UNITS None
set_parameter_property max_code_line ALLOWED_RANGES -2147483648:2147483647
set_parameter_property max_code_line HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point code_interface
# 
add_interface code_interface conduit end
set_interface_property code_interface associatedClock ""
set_interface_property code_interface associatedReset ""
set_interface_property code_interface ENABLED true
set_interface_property code_interface EXPORT_OF ""
set_interface_property code_interface PORT_NAME_MAP ""
set_interface_property code_interface CMSIS_SVD_VARIABLES ""
set_interface_property code_interface SVD_ADDRESS_GROUP ""

add_interface_port code_interface code code Output code_size
add_interface_port code_interface code_index code_index Output 32


# 
# connection point code_control_interface
# 
add_interface code_control_interface conduit end
set_interface_property code_control_interface associatedClock ""
set_interface_property code_control_interface associatedReset ""
set_interface_property code_control_interface ENABLED true
set_interface_property code_control_interface EXPORT_OF ""
set_interface_property code_control_interface PORT_NAME_MAP ""
set_interface_property code_control_interface CMSIS_SVD_VARIABLES ""
set_interface_property code_control_interface SVD_ADDRESS_GROUP ""

add_interface_port code_control_interface active active Input 1
add_interface_port code_control_interface reset reset Input 1


# 
# connection point write_interface
# 
add_interface write_interface conduit end
set_interface_property write_interface associatedClock ""
set_interface_property write_interface associatedReset ""
set_interface_property write_interface ENABLED true
set_interface_property write_interface EXPORT_OF ""
set_interface_property write_interface PORT_NAME_MAP ""
set_interface_property write_interface CMSIS_SVD_VARIABLES ""
set_interface_property write_interface SVD_ADDRESS_GROUP ""

add_interface_port write_interface write_data write_data Input code_size
add_interface_port write_interface is_write is_write Input 1
add_interface_port write_interface write_line write_line Input 32


# 
# connection point enable_interface
# 
add_interface enable_interface conduit end
set_interface_property enable_interface associatedClock ""
set_interface_property enable_interface associatedReset ""
set_interface_property enable_interface ENABLED true
set_interface_property enable_interface EXPORT_OF ""
set_interface_property enable_interface PORT_NAME_MAP ""
set_interface_property enable_interface CMSIS_SVD_VARIABLES ""
set_interface_property enable_interface SVD_ADDRESS_GROUP ""

add_interface_port enable_interface enable enable Input 1

