# TCL File Generated by Component Editor 20.1
# Mon Mar 15 08:46:55 ICT 2021
# DO NOT MODIFY


# 
# decode_to_dense_register "decode_to_dense_register" v1.0
# Wachirawit Wacharak 2021.03.15.08:46:55
# Buffer data between decode and dense
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module decode_to_dense_register
# 
set_module_property DESCRIPTION "Buffer data between decode and dense"
set_module_property NAME decode_to_dense_register
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/registers
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME decode_to_dense_register
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL decode_dense_reg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file decode_dense_reg.sv SYSTEM_VERILOG PATH ../register_delay/registers/decode_dense_reg.sv TOP_LEVEL_FILE
add_fileset_file delay.sv SYSTEM_VERILOG PATH ../register_delay/delay.sv


# 
# parameters
# 
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true
add_parameter data_size INTEGER 16
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true
add_parameter cost_type_size INTEGER 8
set_parameter_property cost_type_size DEFAULT_VALUE 8
set_parameter_property cost_type_size DISPLAY_NAME cost_type_size
set_parameter_property cost_type_size TYPE INTEGER
set_parameter_property cost_type_size UNITS None
set_parameter_property cost_type_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property cost_type_size HDL_PARAMETER true
add_parameter dense_type_size INTEGER 4
set_parameter_property dense_type_size DEFAULT_VALUE 4
set_parameter_property dense_type_size DISPLAY_NAME dense_type_size
set_parameter_property dense_type_size TYPE INTEGER
set_parameter_property dense_type_size UNITS None
set_parameter_property dense_type_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property dense_type_size HDL_PARAMETER true
add_parameter act_type_size INTEGER 4
set_parameter_property act_type_size DEFAULT_VALUE 4
set_parameter_property act_type_size DISPLAY_NAME act_type_size
set_parameter_property act_type_size TYPE INTEGER
set_parameter_property act_type_size UNITS None
set_parameter_property act_type_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property act_type_size HDL_PARAMETER true
add_parameter backprop_controll_size INTEGER 66 ""
set_parameter_property backprop_controll_size DEFAULT_VALUE 66
set_parameter_property backprop_controll_size DISPLAY_NAME backprop_controll_size
set_parameter_property backprop_controll_size TYPE INTEGER
set_parameter_property backprop_controll_size UNITS None
set_parameter_property backprop_controll_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property backprop_controll_size DESCRIPTION ""
set_parameter_property backprop_controll_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point out_weight_interface
# 
add_interface out_weight_interface conduit end
set_interface_property out_weight_interface associatedClock ""
set_interface_property out_weight_interface associatedReset ""
set_interface_property out_weight_interface ENABLED true
set_interface_property out_weight_interface EXPORT_OF ""
set_interface_property out_weight_interface PORT_NAME_MAP ""
set_interface_property out_weight_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_weight_interface SVD_ADDRESS_GROUP ""

add_interface_port out_weight_interface w_out w_stream Output data_size*size
add_interface_port out_weight_interface load_w_out set_w Output 1


# 
# connection point in_weight_interface
# 
add_interface in_weight_interface conduit end
set_interface_property in_weight_interface associatedClock ""
set_interface_property in_weight_interface associatedReset ""
set_interface_property in_weight_interface ENABLED true
set_interface_property in_weight_interface EXPORT_OF ""
set_interface_property in_weight_interface PORT_NAME_MAP ""
set_interface_property in_weight_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_weight_interface SVD_ADDRESS_GROUP ""

add_interface_port in_weight_interface w weight Input data_size*size


# 
# connection point out_input_interface
# 
add_interface out_input_interface conduit end
set_interface_property out_input_interface associatedClock ""
set_interface_property out_input_interface associatedReset ""
set_interface_property out_input_interface ENABLED true
set_interface_property out_input_interface EXPORT_OF ""
set_interface_property out_input_interface PORT_NAME_MAP ""
set_interface_property out_input_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_input_interface SVD_ADDRESS_GROUP ""

add_interface_port out_input_interface x_out data_stream Output data_size*size


# 
# connection point out_forward_interface
# 
add_interface out_forward_interface conduit end
set_interface_property out_forward_interface associatedClock ""
set_interface_property out_forward_interface associatedReset ""
set_interface_property out_forward_interface ENABLED true
set_interface_property out_forward_interface EXPORT_OF ""
set_interface_property out_forward_interface PORT_NAME_MAP ""
set_interface_property out_forward_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_forward_interface SVD_ADDRESS_GROUP ""

add_interface_port out_forward_interface act_type_out act_type Output act_type_size
add_interface_port out_forward_interface cost_type_out cost_type Output cost_type_size
add_interface_port out_forward_interface label_out label Output data_size*size


# 
# connection point out_dense_type_interface
# 
add_interface out_dense_type_interface conduit end
set_interface_property out_dense_type_interface associatedClock ""
set_interface_property out_dense_type_interface associatedReset ""
set_interface_property out_dense_type_interface ENABLED true
set_interface_property out_dense_type_interface EXPORT_OF ""
set_interface_property out_dense_type_interface PORT_NAME_MAP ""
set_interface_property out_dense_type_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_dense_type_interface SVD_ADDRESS_GROUP ""

add_interface_port out_dense_type_interface dense_type_out dense_type Output dense_type_size


# 
# connection point in_typel_interface
# 
add_interface in_typel_interface conduit end
set_interface_property in_typel_interface associatedClock ""
set_interface_property in_typel_interface associatedReset ""
set_interface_property in_typel_interface ENABLED true
set_interface_property in_typel_interface EXPORT_OF ""
set_interface_property in_typel_interface PORT_NAME_MAP ""
set_interface_property in_typel_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_typel_interface SVD_ADDRESS_GROUP ""

add_interface_port in_typel_interface act_type act_type Input act_type_size
add_interface_port in_typel_interface cost_type cost_type Input cost_type_size
add_interface_port in_typel_interface dense_type dense_type Input dense_type_size


# 
# connection point in_control_interface
# 
add_interface in_control_interface conduit end
set_interface_property in_control_interface associatedClock ""
set_interface_property in_control_interface associatedReset ""
set_interface_property in_control_interface ENABLED true
set_interface_property in_control_interface EXPORT_OF ""
set_interface_property in_control_interface PORT_NAME_MAP ""
set_interface_property in_control_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_control_interface SVD_ADDRESS_GROUP ""

add_interface_port in_control_interface load_w load_w Input 1


# 
# connection point in_train_data_interface
# 
add_interface in_train_data_interface conduit end
set_interface_property in_train_data_interface associatedClock ""
set_interface_property in_train_data_interface associatedReset ""
set_interface_property in_train_data_interface ENABLED true
set_interface_property in_train_data_interface EXPORT_OF ""
set_interface_property in_train_data_interface PORT_NAME_MAP ""
set_interface_property in_train_data_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_train_data_interface SVD_ADDRESS_GROUP ""

add_interface_port in_train_data_interface x x Input data_size*size
add_interface_port in_train_data_interface label_in label Input data_size*size


# 
# connection point in_backprop_controll_interface
# 
add_interface in_backprop_controll_interface conduit end
set_interface_property in_backprop_controll_interface associatedClock ""
set_interface_property in_backprop_controll_interface associatedReset ""
set_interface_property in_backprop_controll_interface ENABLED true
set_interface_property in_backprop_controll_interface EXPORT_OF ""
set_interface_property in_backprop_controll_interface PORT_NAME_MAP ""
set_interface_property in_backprop_controll_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_backprop_controll_interface SVD_ADDRESS_GROUP ""

add_interface_port in_backprop_controll_interface backprop_controll backprop_controll Input backprop_controll_size


# 
# connection point out_backprop_controll_interface
# 
add_interface out_backprop_controll_interface conduit end
set_interface_property out_backprop_controll_interface associatedClock ""
set_interface_property out_backprop_controll_interface associatedReset ""
set_interface_property out_backprop_controll_interface ENABLED true
set_interface_property out_backprop_controll_interface EXPORT_OF ""
set_interface_property out_backprop_controll_interface PORT_NAME_MAP ""
set_interface_property out_backprop_controll_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_backprop_controll_interface SVD_ADDRESS_GROUP ""

add_interface_port out_backprop_controll_interface backprop_controll_out backprop_controll Output backprop_controll_size

