# TCL File Generated by Component Editor 20.1
# Tue Jan 19 00:19:21 ICT 2021
# DO NOT MODIFY


# 
# backprop_controller "backprop_controller" v1.0
# Wachirawit Wacharak 2021.01.19.00:19:21
# Create control sugnal for backprop layer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module backprop_controller
# 
set_module_property DESCRIPTION "Create control sugnal for backprop layer"
set_module_property NAME backprop_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/backprop_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME backprop_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL backprop_stack_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file backprop_stack_controller.sv SYSTEM_VERILOG PATH ../backprop_stack_controller/backprop_stack_controller.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true
add_parameter data_size INTEGER 16
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true
add_parameter backprop_controll_size INTEGER 100
set_parameter_property backprop_controll_size DEFAULT_VALUE 100
set_parameter_property backprop_controll_size DISPLAY_NAME backprop_controll_size
set_parameter_property backprop_controll_size TYPE INTEGER
set_parameter_property backprop_controll_size UNITS None
set_parameter_property backprop_controll_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property backprop_controll_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point backprop_controll_out_interface
# 
add_interface backprop_controll_out_interface conduit end
set_interface_property backprop_controll_out_interface associatedClock ""
set_interface_property backprop_controll_out_interface associatedReset ""
set_interface_property backprop_controll_out_interface ENABLED true
set_interface_property backprop_controll_out_interface EXPORT_OF ""
set_interface_property backprop_controll_out_interface PORT_NAME_MAP ""
set_interface_property backprop_controll_out_interface CMSIS_SVD_VARIABLES ""
set_interface_property backprop_controll_out_interface SVD_ADDRESS_GROUP ""

add_interface_port backprop_controll_out_interface current_layer_out current_layer Output 32
add_interface_port backprop_controll_out_interface dc_dw_layer_out dc_dw_layer Output 32
add_interface_port backprop_controll_out_interface dc_dw_row_out dc_dw_row Output 32
add_interface_port backprop_controll_out_interface update_storage_out update_storage Output 1
add_interface_port backprop_controll_out_interface update_dy_dy_old_out update_dy_dy_old Output 1
add_interface_port backprop_controll_out_interface cal_dc_dw_out cal_dc_dw Output 1
add_interface_port backprop_controll_out_interface reset_out reset Output 1


# 
# connection point backprop_controll_bundle_in_interface
# 
add_interface backprop_controll_bundle_in_interface conduit end
set_interface_property backprop_controll_bundle_in_interface associatedClock ""
set_interface_property backprop_controll_bundle_in_interface associatedReset ""
set_interface_property backprop_controll_bundle_in_interface ENABLED true
set_interface_property backprop_controll_bundle_in_interface EXPORT_OF ""
set_interface_property backprop_controll_bundle_in_interface PORT_NAME_MAP ""
set_interface_property backprop_controll_bundle_in_interface CMSIS_SVD_VARIABLES ""
set_interface_property backprop_controll_bundle_in_interface SVD_ADDRESS_GROUP ""

add_interface_port backprop_controll_bundle_in_interface backprop_controll_bundle backprop_controll Input backprop_controll_size


# 
# connection point cal_dc_dw_out_forward_interface
# 
add_interface cal_dc_dw_out_forward_interface conduit end
set_interface_property cal_dc_dw_out_forward_interface associatedClock ""
set_interface_property cal_dc_dw_out_forward_interface associatedReset ""
set_interface_property cal_dc_dw_out_forward_interface ENABLED true
set_interface_property cal_dc_dw_out_forward_interface EXPORT_OF ""
set_interface_property cal_dc_dw_out_forward_interface PORT_NAME_MAP ""
set_interface_property cal_dc_dw_out_forward_interface CMSIS_SVD_VARIABLES ""
set_interface_property cal_dc_dw_out_forward_interface SVD_ADDRESS_GROUP ""

add_interface_port cal_dc_dw_out_forward_interface cal_dc_dw_out_forward cal_dc_dw Output 1


# 
# connection point out_weight_interface
# 
add_interface out_weight_interface conduit end
set_interface_property out_weight_interface associatedClock ""
set_interface_property out_weight_interface associatedReset ""
set_interface_property out_weight_interface ENABLED true
set_interface_property out_weight_interface EXPORT_OF ""
set_interface_property out_weight_interface PORT_NAME_MAP ""
set_interface_property out_weight_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_weight_interface SVD_ADDRESS_GROUP ""

add_interface_port out_weight_interface weight_row weight_row Output 32
add_interface_port out_weight_interface weight_layer weight_layer Output 32

