# TCL File Generated by Component Editor 20.1
# Mon Mar 15 20:18:55 ICT 2021
# DO NOT MODIFY


# 
# diff_to_decode_register "diff_to_decode_register" v1.0
# Wachirawit Wacharak 2021.03.15.20:18:55
# Buffer databetween diff to decode
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module diff_to_decode_register
# 
set_module_property DESCRIPTION "Buffer databetween diff to decode"
set_module_property NAME diff_to_decode_register
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/registers
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME diff_to_decode_register
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL diff_to_decode_register
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file diff_to_decode_register.sv SYSTEM_VERILOG PATH ../register_delay/registers/diff_to_decode_register.sv TOP_LEVEL_FILE
add_fileset_file delay.sv SYSTEM_VERILOG PATH ../register_delay/delay.sv


# 
# parameters
# 
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true
add_parameter data_size INTEGER 16
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point in_x_and_label_interface
# 
add_interface in_x_and_label_interface conduit end
set_interface_property in_x_and_label_interface associatedClock ""
set_interface_property in_x_and_label_interface associatedReset ""
set_interface_property in_x_and_label_interface ENABLED true
set_interface_property in_x_and_label_interface EXPORT_OF ""
set_interface_property in_x_and_label_interface PORT_NAME_MAP ""
set_interface_property in_x_and_label_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_x_and_label_interface SVD_ADDRESS_GROUP ""

add_interface_port in_x_and_label_interface z z Input data_size*size
add_interface_port in_x_and_label_interface predict_value label Input data_size*size


# 
# connection point out_x_and_label_interface
# 
add_interface out_x_and_label_interface conduit end
set_interface_property out_x_and_label_interface associatedClock ""
set_interface_property out_x_and_label_interface associatedReset ""
set_interface_property out_x_and_label_interface ENABLED true
set_interface_property out_x_and_label_interface EXPORT_OF ""
set_interface_property out_x_and_label_interface PORT_NAME_MAP ""
set_interface_property out_x_and_label_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_x_and_label_interface SVD_ADDRESS_GROUP ""

add_interface_port out_x_and_label_interface z_out z Output data_size*size
add_interface_port out_x_and_label_interface predict_value_out label Output data_size*size


# 
# connection point out_update_weight_interface
# 
add_interface out_update_weight_interface conduit end
set_interface_property out_update_weight_interface associatedClock ""
set_interface_property out_update_weight_interface associatedReset ""
set_interface_property out_update_weight_interface ENABLED true
set_interface_property out_update_weight_interface EXPORT_OF ""
set_interface_property out_update_weight_interface PORT_NAME_MAP ""
set_interface_property out_update_weight_interface CMSIS_SVD_VARIABLES ""
set_interface_property out_update_weight_interface SVD_ADDRESS_GROUP ""

add_interface_port out_update_weight_interface update_weight_out is_update_weight Output 1
add_interface_port out_update_weight_interface w_layer_index_out update_weight_layer Output 32
add_interface_port out_update_weight_interface w_row_index_out update_weight_row Output 32
add_interface_port out_update_weight_interface dc_dw_out update_weight_value Output data_size*size


# 
# connection point in_update_weight_interface
# 
add_interface in_update_weight_interface conduit end
set_interface_property in_update_weight_interface associatedClock ""
set_interface_property in_update_weight_interface associatedReset ""
set_interface_property in_update_weight_interface ENABLED true
set_interface_property in_update_weight_interface EXPORT_OF ""
set_interface_property in_update_weight_interface PORT_NAME_MAP ""
set_interface_property in_update_weight_interface CMSIS_SVD_VARIABLES ""
set_interface_property in_update_weight_interface SVD_ADDRESS_GROUP ""

add_interface_port in_update_weight_interface dc_dw update_weight_value Input data_size*size
add_interface_port in_update_weight_interface w_layer_index update_weight_layer Input 32
add_interface_port in_update_weight_interface w_row_index update_weight_row Input 32
add_interface_port in_update_weight_interface update_weight is_update_weight Input 1

