# TCL File Generated by Component Editor 20.1
# Fri Mar 19 01:37:02 ICT 2021
# DO NOT MODIFY


# 
# fetch_to_decode_register "fetch_to_decode_register" v1.0
# Wachirawit Wacharak 2021.03.19.01:37:02
# Register between fetch and decode layer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fetch_to_decode_register
# 
set_module_property DESCRIPTION "Register between fetch and decode layer"
set_module_property NAME fetch_to_decode_register
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/registers
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME fetch_to_decode_register
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fetch_decode_reg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file delay.sv SYSTEM_VERILOG PATH ../register_delay/delay.sv
add_fileset_file fetch_decode_reg.sv SYSTEM_VERILOG PATH ../register_delay/registers/fetch_decode_reg.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter code_size INTEGER 12
set_parameter_property code_size DEFAULT_VALUE 12
set_parameter_property code_size DISPLAY_NAME code_size
set_parameter_property code_size TYPE INTEGER
set_parameter_property code_size UNITS None
set_parameter_property code_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property code_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point code_interface
# 
add_interface code_interface conduit end
set_interface_property code_interface associatedClock ""
set_interface_property code_interface associatedReset ""
set_interface_property code_interface ENABLED true
set_interface_property code_interface EXPORT_OF ""
set_interface_property code_interface PORT_NAME_MAP ""
set_interface_property code_interface CMSIS_SVD_VARIABLES ""
set_interface_property code_interface SVD_ADDRESS_GROUP ""

add_interface_port code_interface code code Input code_size
add_interface_port code_interface code_index code_index Input 32


# 
# connection point code_out_interface
# 
add_interface code_out_interface conduit end
set_interface_property code_out_interface associatedClock ""
set_interface_property code_out_interface associatedReset ""
set_interface_property code_out_interface ENABLED true
set_interface_property code_out_interface EXPORT_OF ""
set_interface_property code_out_interface PORT_NAME_MAP ""
set_interface_property code_out_interface CMSIS_SVD_VARIABLES ""
set_interface_property code_out_interface SVD_ADDRESS_GROUP ""

add_interface_port code_out_interface code_out code Output code_size


# 
# connection point code_index_out_interface
# 
add_interface code_index_out_interface conduit end
set_interface_property code_index_out_interface associatedClock ""
set_interface_property code_index_out_interface associatedReset ""
set_interface_property code_index_out_interface ENABLED true
set_interface_property code_index_out_interface EXPORT_OF ""
set_interface_property code_index_out_interface PORT_NAME_MAP ""
set_interface_property code_index_out_interface CMSIS_SVD_VARIABLES ""
set_interface_property code_index_out_interface SVD_ADDRESS_GROUP ""

add_interface_port code_index_out_interface code_index_out code_index Output 32

