# TCL File Generated by Component Editor 20.1
# Fri Jan 01 21:01:08 ICT 2021
# DO NOT MODIFY


# 
# is_load_spreader "is_load_spreader" v1.0
#  2021.01.01.21:01:08
# Split is_load signal
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module is_load_spreader
# 
set_module_property DESCRIPTION "Split is_load signal"
set_module_property NAME is_load_spreader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/decode_layer
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME is_load_spreader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spreader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spreader.sv SYSTEM_VERILOG PATH ../spreader/spreader.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter size INTEGER 1
set_parameter_property size DEFAULT_VALUE 1
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point is_load_2
# 
add_interface is_load_2 conduit end
set_interface_property is_load_2 associatedClock ""
set_interface_property is_load_2 associatedReset ""
set_interface_property is_load_2 ENABLED true
set_interface_property is_load_2 EXPORT_OF ""
set_interface_property is_load_2 PORT_NAME_MAP ""
set_interface_property is_load_2 CMSIS_SVD_VARIABLES ""
set_interface_property is_load_2 SVD_ADDRESS_GROUP ""

add_interface_port is_load_2 data_out_b is_load Output size


# 
# connection point is_load_1
# 
add_interface is_load_1 conduit end
set_interface_property is_load_1 associatedClock ""
set_interface_property is_load_1 associatedReset ""
set_interface_property is_load_1 ENABLED true
set_interface_property is_load_1 EXPORT_OF ""
set_interface_property is_load_1 PORT_NAME_MAP ""
set_interface_property is_load_1 CMSIS_SVD_VARIABLES ""
set_interface_property is_load_1 SVD_ADDRESS_GROUP ""

add_interface_port is_load_1 data_out_a is_load Output size


# 
# connection point is_load
# 
add_interface is_load conduit end
set_interface_property is_load associatedClock ""
set_interface_property is_load associatedReset ""
set_interface_property is_load ENABLED true
set_interface_property is_load EXPORT_OF ""
set_interface_property is_load PORT_NAME_MAP ""
set_interface_property is_load CMSIS_SVD_VARIABLES ""
set_interface_property is_load SVD_ADDRESS_GROUP ""

add_interface_port is_load data_in is_load Input size

