# TCL File Generated by Component Editor 20.1
# Sat Jan 02 00:50:46 ICT 2021
# DO NOT MODIFY


# 
# matrix_storage_locator "matrix_storage_locator" v1.0
# Wachirawit Wacharak 2021.01.02.00:50:46
# Use to locate the address of matrix
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module matrix_storage_locator
# 
set_module_property DESCRIPTION "Use to locate the address of matrix"
set_module_property NAME matrix_storage_locator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/decode_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME matrix_storage_locator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matrix_storage_locator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file matrix_storage_locator.sv SYSTEM_VERILOG PATH ../matrix_storage_locator/matrix_storage_locator.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_interface
# 
add_interface reset_interface conduit end
set_interface_property reset_interface associatedClock ""
set_interface_property reset_interface associatedReset ""
set_interface_property reset_interface ENABLED true
set_interface_property reset_interface EXPORT_OF ""
set_interface_property reset_interface PORT_NAME_MAP ""
set_interface_property reset_interface CMSIS_SVD_VARIABLES ""
set_interface_property reset_interface SVD_ADDRESS_GROUP ""

add_interface_port reset_interface reset reset Input 1


# 
# connection point matrix_location_interface
# 
add_interface matrix_location_interface conduit end
set_interface_property matrix_location_interface associatedClock ""
set_interface_property matrix_location_interface associatedReset ""
set_interface_property matrix_location_interface ENABLED true
set_interface_property matrix_location_interface EXPORT_OF ""
set_interface_property matrix_location_interface PORT_NAME_MAP ""
set_interface_property matrix_location_interface CMSIS_SVD_VARIABLES ""
set_interface_property matrix_location_interface SVD_ADDRESS_GROUP ""

add_interface_port matrix_location_interface layer_index layer_index Output 32
add_interface_port matrix_location_interface row_index row_index Output 32


# 
# connection point is_load_interface
# 
add_interface is_load_interface conduit end
set_interface_property is_load_interface associatedClock ""
set_interface_property is_load_interface associatedReset ""
set_interface_property is_load_interface ENABLED true
set_interface_property is_load_interface EXPORT_OF ""
set_interface_property is_load_interface PORT_NAME_MAP ""
set_interface_property is_load_interface CMSIS_SVD_VARIABLES ""
set_interface_property is_load_interface SVD_ADDRESS_GROUP ""

add_interface_port is_load_interface is_load is_load Input 1

