# TCL File Generated by Component Editor 20.1
# Sat Jan 02 00:53:36 ICT 2021
# DO NOT MODIFY


# 
# matrix_location_spreader "matrix_location_spreader" v1.0
#  2021.01.02.00:53:36
# Split matrix location signal
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module matrix_location_spreader
# 
set_module_property DESCRIPTION "Split matrix location signal"
set_module_property NAME matrix_location_spreader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/decode_layer
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME matrix_location_spreader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matrix_location_spreader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spreader.sv SYSTEM_VERILOG PATH ../spreader/spreader.sv
add_fileset_file matrix_location_spreader.sv SYSTEM_VERILOG PATH ../spreader/spreaders/matrix_location_spreader.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter layer_index_size INTEGER 32
set_parameter_property layer_index_size DEFAULT_VALUE 32
set_parameter_property layer_index_size DISPLAY_NAME layer_index_size
set_parameter_property layer_index_size TYPE INTEGER
set_parameter_property layer_index_size UNITS None
set_parameter_property layer_index_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property layer_index_size HDL_PARAMETER true
add_parameter row_index_size INTEGER 32 ""
set_parameter_property row_index_size DEFAULT_VALUE 32
set_parameter_property row_index_size DISPLAY_NAME row_index_size
set_parameter_property row_index_size TYPE INTEGER
set_parameter_property row_index_size UNITS None
set_parameter_property row_index_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property row_index_size DESCRIPTION ""
set_parameter_property row_index_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point matrix_location_interface
# 
add_interface matrix_location_interface conduit end
set_interface_property matrix_location_interface associatedClock ""
set_interface_property matrix_location_interface associatedReset ""
set_interface_property matrix_location_interface ENABLED true
set_interface_property matrix_location_interface EXPORT_OF ""
set_interface_property matrix_location_interface PORT_NAME_MAP ""
set_interface_property matrix_location_interface CMSIS_SVD_VARIABLES ""
set_interface_property matrix_location_interface SVD_ADDRESS_GROUP ""

add_interface_port matrix_location_interface read_row_index row_index Input row_index_size
add_interface_port matrix_location_interface read_layer_index layer_index Input layer_index_size


# 
# connection point matrix_location_out_1_interface
# 
add_interface matrix_location_out_1_interface conduit end
set_interface_property matrix_location_out_1_interface associatedClock ""
set_interface_property matrix_location_out_1_interface associatedReset ""
set_interface_property matrix_location_out_1_interface ENABLED true
set_interface_property matrix_location_out_1_interface EXPORT_OF ""
set_interface_property matrix_location_out_1_interface PORT_NAME_MAP ""
set_interface_property matrix_location_out_1_interface CMSIS_SVD_VARIABLES ""
set_interface_property matrix_location_out_1_interface SVD_ADDRESS_GROUP ""

add_interface_port matrix_location_out_1_interface read_row_index_1 row_index Output row_index_size
add_interface_port matrix_location_out_1_interface read_layer_index_1 layer_index Output layer_index_size


# 
# connection point matrix_location_out_2_interface
# 
add_interface matrix_location_out_2_interface conduit end
set_interface_property matrix_location_out_2_interface associatedClock ""
set_interface_property matrix_location_out_2_interface associatedReset ""
set_interface_property matrix_location_out_2_interface ENABLED true
set_interface_property matrix_location_out_2_interface EXPORT_OF ""
set_interface_property matrix_location_out_2_interface PORT_NAME_MAP ""
set_interface_property matrix_location_out_2_interface CMSIS_SVD_VARIABLES ""
set_interface_property matrix_location_out_2_interface SVD_ADDRESS_GROUP ""

add_interface_port matrix_location_out_2_interface read_layer_index_2 layer_index Output layer_index_size
add_interface_port matrix_location_out_2_interface read_row_index_2 row_index Output row_index_size

