# TCL File Generated by Component Editor 20.1
# Sat Jan 02 16:23:33 ICT 2021
# DO NOT MODIFY


# 
# matrix_storage "matrix_storage" v1.0
# Wachirawit Wacharak 2021.01.02.16:23:33
# Use to store matrix
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module matrix_storage
# 
set_module_property DESCRIPTION "Use to store matrix"
set_module_property NAME matrix_storage
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/decode_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME matrix_storage
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matrix_storage
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file matrix_storage.sv SYSTEM_VERILOG PATH ../matrix_storage/matrix_storage.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true
add_parameter data_size INTEGER 16
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true
add_parameter max_layer INTEGER 5
set_parameter_property max_layer DEFAULT_VALUE 5
set_parameter_property max_layer DISPLAY_NAME max_layer
set_parameter_property max_layer TYPE INTEGER
set_parameter_property max_layer UNITS None
set_parameter_property max_layer ALLOWED_RANGES -2147483648:2147483647
set_parameter_property max_layer HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point matrix_location_interface
# 
add_interface matrix_location_interface conduit end
set_interface_property matrix_location_interface associatedClock ""
set_interface_property matrix_location_interface associatedReset ""
set_interface_property matrix_location_interface ENABLED true
set_interface_property matrix_location_interface EXPORT_OF ""
set_interface_property matrix_location_interface PORT_NAME_MAP ""
set_interface_property matrix_location_interface CMSIS_SVD_VARIABLES ""
set_interface_property matrix_location_interface SVD_ADDRESS_GROUP ""

add_interface_port matrix_location_interface read_layer_index layer_index Input 32
add_interface_port matrix_location_interface read_row_index row_index Input 32


# 
# connection point write_interface
# 
add_interface write_interface conduit end
set_interface_property write_interface associatedClock ""
set_interface_property write_interface associatedReset ""
set_interface_property write_interface ENABLED true
set_interface_property write_interface EXPORT_OF ""
set_interface_property write_interface PORT_NAME_MAP ""
set_interface_property write_interface CMSIS_SVD_VARIABLES ""
set_interface_property write_interface SVD_ADDRESS_GROUP ""

add_interface_port write_interface write_layer_index write_layer_index Input 32
add_interface_port write_interface write_row_index write_row_index Input 32
add_interface_port write_interface write_data write_data Input data_size*size


# 
# connection point read_data_interface
# 
add_interface read_data_interface conduit end
set_interface_property read_data_interface associatedClock ""
set_interface_property read_data_interface associatedReset ""
set_interface_property read_data_interface ENABLED true
set_interface_property read_data_interface EXPORT_OF ""
set_interface_property read_data_interface PORT_NAME_MAP ""
set_interface_property read_data_interface CMSIS_SVD_VARIABLES ""
set_interface_property read_data_interface SVD_ADDRESS_GROUP ""

add_interface_port read_data_interface read_data read_data Output data_size*size


# 
# connection point is_write_interface
# 
add_interface is_write_interface conduit end
set_interface_property is_write_interface associatedClock ""
set_interface_property is_write_interface associatedReset ""
set_interface_property is_write_interface ENABLED true
set_interface_property is_write_interface EXPORT_OF ""
set_interface_property is_write_interface PORT_NAME_MAP ""
set_interface_property is_write_interface CMSIS_SVD_VARIABLES ""
set_interface_property is_write_interface SVD_ADDRESS_GROUP ""

add_interface_port is_write_interface is_write is_write Input 1


# 
# connection point is_read_interface
# 
add_interface is_read_interface conduit end
set_interface_property is_read_interface associatedClock ""
set_interface_property is_read_interface associatedReset ""
set_interface_property is_read_interface ENABLED true
set_interface_property is_read_interface EXPORT_OF ""
set_interface_property is_read_interface PORT_NAME_MAP ""
set_interface_property is_read_interface CMSIS_SVD_VARIABLES ""
set_interface_property is_read_interface SVD_ADDRESS_GROUP ""

add_interface_port is_read_interface is_read is_load Input 1

