# TCL File Generated by Component Editor 20.1
# Thu Jan 07 22:42:57 ICT 2021
# DO NOT MODIFY


# 
# mult_matrix_prep "mult_matrix_prep" v1.0
# Wachirawit Wacharak 2021.01.07.22:42:57
# Matrix preparation for multiprecation
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mult_matrix_prep
# 
set_module_property DESCRIPTION "Matrix preparation for multiprecation"
set_module_property NAME mult_matrix_prep
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/dense_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME mult_matrix_prep
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mult_matrix_prep
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mult_matrix_prep.sv SYSTEM_VERILOG PATH ../mult_matrix_prep/mult_matrix_prep.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_size INTEGER 16 ""
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size DESCRIPTION ""
set_parameter_property data_size HDL_PARAMETER true
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point input_stream_interface
# 
add_interface input_stream_interface conduit end
set_interface_property input_stream_interface associatedClock ""
set_interface_property input_stream_interface associatedReset ""
set_interface_property input_stream_interface ENABLED true
set_interface_property input_stream_interface EXPORT_OF ""
set_interface_property input_stream_interface PORT_NAME_MAP ""
set_interface_property input_stream_interface CMSIS_SVD_VARIABLES ""
set_interface_property input_stream_interface SVD_ADDRESS_GROUP ""

add_interface_port input_stream_interface input_stream data_stream Input data_size*size


# 
# connection point output_stream_interface
# 
add_interface output_stream_interface conduit end
set_interface_property output_stream_interface associatedClock ""
set_interface_property output_stream_interface associatedReset ""
set_interface_property output_stream_interface ENABLED true
set_interface_property output_stream_interface EXPORT_OF ""
set_interface_property output_stream_interface PORT_NAME_MAP ""
set_interface_property output_stream_interface CMSIS_SVD_VARIABLES ""
set_interface_property output_stream_interface SVD_ADDRESS_GROUP ""

add_interface_port output_stream_interface output_stream data_stream Output data_size*size

