# TCL File Generated by Component Editor 20.1
# Mon Jan 11 00:40:00 ICT 2021
# DO NOT MODIFY


# 
# train_data_mux "train_data_mux" v1.0
# Wachirawit Wacharak 2021.01.11.00:40:00
# Select data between z and x
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module train_data_mux
# 
set_module_property DESCRIPTION "Select data between z and x"
set_module_property NAME train_data_mux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP neural_burning/decode_layer
set_module_property AUTHOR "Wachirawit Wacharak"
set_module_property DISPLAY_NAME train_data_mux
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL train_data_mux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file train_data_mux.sv SYSTEM_VERILOG PATH ../train_data_mux/train_data_mux.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_size INTEGER 16
set_parameter_property data_size DEFAULT_VALUE 16
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true
add_parameter size INTEGER 3
set_parameter_property size DEFAULT_VALUE 3
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point use_z_interface
# 
add_interface use_z_interface conduit end
set_interface_property use_z_interface associatedClock ""
set_interface_property use_z_interface associatedReset ""
set_interface_property use_z_interface ENABLED true
set_interface_property use_z_interface EXPORT_OF ""
set_interface_property use_z_interface PORT_NAME_MAP ""
set_interface_property use_z_interface CMSIS_SVD_VARIABLES ""
set_interface_property use_z_interface SVD_ADDRESS_GROUP ""

add_interface_port use_z_interface use_z use_z Input 1


# 
# connection point use_z_data_interface
# 
add_interface use_z_data_interface conduit end
set_interface_property use_z_data_interface associatedClock ""
set_interface_property use_z_data_interface associatedReset ""
set_interface_property use_z_data_interface ENABLED true
set_interface_property use_z_data_interface EXPORT_OF ""
set_interface_property use_z_data_interface PORT_NAME_MAP ""
set_interface_property use_z_data_interface CMSIS_SVD_VARIABLES ""
set_interface_property use_z_data_interface SVD_ADDRESS_GROUP ""

add_interface_port use_z_data_interface z z Input data_size*size
add_interface_port use_z_data_interface predict_value_old label Input data_size*size


# 
# connection point select_data_interface
# 
add_interface select_data_interface conduit end
set_interface_property select_data_interface associatedClock ""
set_interface_property select_data_interface associatedReset ""
set_interface_property select_data_interface ENABLED true
set_interface_property select_data_interface EXPORT_OF ""
set_interface_property select_data_interface PORT_NAME_MAP ""
set_interface_property select_data_interface CMSIS_SVD_VARIABLES ""
set_interface_property select_data_interface SVD_ADDRESS_GROUP ""

add_interface_port select_data_interface data_out x Output data_size*size
add_interface_port select_data_interface predict_value_out label Output data_size*size


# 
# connection point use_x_data_x_interface
# 
add_interface use_x_data_x_interface conduit end
set_interface_property use_x_data_x_interface associatedClock ""
set_interface_property use_x_data_x_interface associatedReset ""
set_interface_property use_x_data_x_interface ENABLED true
set_interface_property use_x_data_x_interface EXPORT_OF ""
set_interface_property use_x_data_x_interface PORT_NAME_MAP ""
set_interface_property use_x_data_x_interface CMSIS_SVD_VARIABLES ""
set_interface_property use_x_data_x_interface SVD_ADDRESS_GROUP ""

add_interface_port use_x_data_x_interface x read_data Input data_size*size


# 
# connection point use_x_data_label_interface
# 
add_interface use_x_data_label_interface conduit end
set_interface_property use_x_data_label_interface associatedClock ""
set_interface_property use_x_data_label_interface associatedReset ""
set_interface_property use_x_data_label_interface ENABLED true
set_interface_property use_x_data_label_interface EXPORT_OF ""
set_interface_property use_x_data_label_interface PORT_NAME_MAP ""
set_interface_property use_x_data_label_interface CMSIS_SVD_VARIABLES ""
set_interface_property use_x_data_label_interface SVD_ADDRESS_GROUP ""

add_interface_port use_x_data_label_interface predict_value read_data Input data_size*size

